# https://travis-ci.org/solus-impar/slack-events
language: python
python:
    - 3.5
    - 3.6
install:
    - pip3 install -r requirements.txt
    - pip3 install -e .
script:
    - python3 -m pytest
    - slack-events
